### ISSUE TITLE
unknown log_hier_method: "text" found in line ...

### ISSUE THREAD

**Issue by hildeb** [C0RD/calamaris#1]
```
unknown log_hier_method: "text" found in line 22516752 of input:
 1642078013.251    519 172.29.224.246 TCP_DENIED/403 3984 CONNECT:28355 - HIER_NONE/- text/html accessRule=notsslports -

unknown log_hier_method: "text" found in line 22830996 of input:
 1642078395.416    305 172.29.224.246 TCP_DENIED/403 3984 CONNECT:31735 - HIER_NONE/- text/html accessRule=notsslports -

unknown log_hier_method: "text" found in line 22831247 of input:
 1642078395.648    536 172.29.224.246 TCP_DENIED/403 3984 CONNECT:31735 - HIER_NONE/- text/html accessRule=notsslports -

unknown log_hier_method: "text" found in line 22833281 of input:
 1642078398.094      0 172.29.224.246 TCP_DENIED/403 3984 CONNECT:31735 - HIER_NONE/- text/html accessRule=notsslports -

unknown log_hier_method: "text" found in line 23075137 of input:
 1642078698.065    220 172.29.224.246 TCP_DENIED/403 3984 CONNECT:29036 - HIER_NONE/- text/html accessRule=notsslports -

```

**Comment by hildeb** [comment]
This is squid-6.0.0-20220111-r166fb9182

**Comment by C0RD** [comment]
Looking at http://lists.squid-cache.org/pipermail/squid-users/2020-September/022756.html this seems to be a bug in Squid... 

Not sure if I should do something about it.

**Comment by fanto666** [comment]
I got the same error with squid 4.13:

unknown log_hier_method: "text" found in line 1797650 of input:
 1722837946.931      0 10.55.21.133 TCP_DENIED/403 3855 CONNECT:8802 - HIER_NONE/- text/html "-"

original log line:

1722837946.931      0 10.55.21.133 TCP_DENIED/403 3855 CONNECT [2620:123:2041:14:149:137:14:175]:8802 - HIER_NONE/- text/html "-"

the log lines are caused by port 8802 not being allowed and ipv6 address being used. The same CONNECT with ipv4 address is not reported as error:

1722837946.931      0 10.55.21.133 TCP_DENIED/403 3780 CONNECT 149.137.14.175:8802 - HIER_NONE/- text/html "-"

I hope this helps.

**Comment by C0RD** [comment]
@fanto666 I just came around to test your original line above, and could not reproduce the error. (using Calamaris 2.99.4.7)

But just to understand this correctly: the error message it produces differs from the input line from the squid log?

**Comment by fanto666** [comment]
Yes, I pasted error as received from calamaris 
and full original line from squid output. 

Log format is set to squid-extended.

I guess that the ipv6 addresses enclosed in [] is somehow dropped and results in the error

**Comment by C0RD** [comment]
Hallo! Du (fanto666) hast geschrieben:

>Yes, I pasted error as received from calamaris 
>and full original line from squid output. 
>
>Log format is set to squid-extended.
>
>I guess that the ipv6 addresses enclosed in [] is somehow dropped and results in the error

The Log File Format was the mssing bit. I can reproduce it now.  (when I run
calamaris -av on that line, it guesses it is netcache-format and is just
happy)

Cord
